name: Android Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit + Instrumented Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Start Android Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: default
          arch: x86_64
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unitTest-report
          path: app/build/reports/tests/testDebugUnitTest

      - name: Upload Instrumented Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: androidTest-report
          path: app/build/reports/androidTests/connected
