name: Android Tests

on:
  pull_request:
    branches:
      - main  # or whatever your default branch is

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      # Optional: if you have instrumented tests
      # - name: Run Instrumented Tests (requires emulator setup)
      #   run: ./gradlew connectedDebugAndroidTest
